### ISSUE TITLE
No License?

### ISSUE THREAD

**Issue by fire** [KCIV/VGheatmap#1]
What license is the code under?

**Comment by KCIV** [comment]
It is listed in the description file as GPL-3. https://www.gnu.org/licenses/quick-guide-gplv3.html

If you have any more questions let me know.

**Comment by fire** [comment]
Oh, I guess I'll just look at something else then, thank you for your efforts though. I tend to expect things in game development to be MIT license so that people and companies can remix it.

**Comment by KCIV** [comment]
In what way does the MIT license differ from the GPL-3 for your use? Unless I am mistaken, GPL-3 allows free use and distribution of any changes or derivatives.

Also this is an R package. The vast majority of which are hosted by CRAN are under various forms of GPL.

If there is a specific plan or goal you have which the GPL license prohibits? I am open to exploring other licenses.
